### ISSUE TITLE
Slow scanning mode - fragile documents

### ISSUE THREAD

**Issue by petrjac** [twain/twain-direct#16]
Please, is it implemented mode for slow scanning?

I have successfully tried to `sendTask` and and bridge (with connected Alaris S2070) returned:
```json
...
{
  "attribute": "sheetHandling",
  "values": [
    {
      "value": "fragile"
    }
  ]
},
...
```

But it seems to have **no effect** on scanning speed.

**Comment by mlmcl62** [comment]
The Bridge turns the fragile request into:  "CAP_PAPERHANDLING,TWON_ONEVALUE,TWTY_UINT16,1", where the value 1 is FRAGLE.  Looking at the S2000 driver I see that's not being mapped to anything.  CAP_PAPERHANDLING is only reporting support for NORMAL.  So, sadly, that's an issue for that particular scanner driver.

**Comment by mlmcl62** [comment]
I'm closing this because it's not a TWAIN Direct issue...
