### ISSUE TITLE
[Help] Open .wixproj project

### ISSUE THREAD

**Issue by khoipt** [twain/twain-direct#2]
I see that there are `TwainDirect.App.Installer`, `TwainDirect.Scanner.Installer` in solution but can't open them. I try to install WIX but still can't open them.

Please help me how to open it.

I'm using Microsoft Visual Studio Community 2015 Version 14.0.25431.01 Update 3

**Comment by kolomiets** [comment]
It is not super-convenient at the moment :-\ I definitely need to improve that.
You need to restore nuget packages to download Wix assemblies we are reffering to:
 - [optional] [Download nuget](https://dist.nuget.org/index.html) (if you don't have it already)
 - Install [Wix](http://wixtoolset.org/) to add installer project types in Visual Studio
 - Restore packages by running ```nuget.exe restore TwainDirect.sln```

I've update project's README file with these steps.

**Comment by khoipt** [comment]
Thank you. It works well. I can build the installer.
